on:
  push:
    branches:
      - main
env:
  BUCKET: bucket2-ctp-gcp


jobs:
  terraform_apply:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.CTP_SECRET_KEY }}
          export_default_credentials: true
          #version: '>= 363.0.0'


      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CTP_SECRET_KEY }}

#      - name: Configure Docker (si nécessaire)
#        run: gcloud auth configure-docker

      - name: Build image cloud
        working-directory: ./application
        run: gcloud builds submit --tag gcr.io/ctpgcp/flask-ctp-ci-cd .


      - name: Terraform Init
        run: terraform init


      - name: Terraform Plan
        run: terraform plan


      - name: Terraform Apply
        run: terraform apply -auto-approve
